apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-api
  namespace: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-api
  template:
    metadata:
      labels:
        app: capstone-api
    spec:
      containers:
        - name: api
          image: ghcr.io/YOUR_GITHUB_USER/capstone-api:latest
          ports:
            - containerPort: 8000
